<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Sensor Dashboard</title>
    <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
    <style>
        body {
            margin: 50px 0 0 0;
            padding: 0;
            width: 100%;
            font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
            color: #aaa;
            font-size: 18px;
        }
        h1 {
            color: #719e40;
            letter-spacing: -3px;
            font-family: 'Lato', sans-serif;
            font-size: 100px;
            font-weight: 200;
            margin-bottom: 0;
        }

        .grid-container {
            display: grid;
            align-items: center;
            grid-template-columns: 2fr 0.2fr 0.2fr 0.5fr 2fr;
        }

        .nameHeading {
            font-weight:bold;
            color:black;

            justify-self: center;
            padding-bottom: 1em;

            grid-column-start: 1;
            grid-column-end: 1;
            grid-row-start: 1;
            grid-row-end: 1;
        }

        .statusHeading {
            font-weight:bold;
            color:black;

            justify-self: center;
            padding-bottom: 1em;

            grid-column-start: 2;
            grid-column-end: 2;
            grid-row-start: 1;
            grid-row-end: 1;
        }

        .statusCodeHeading {
            font-weight:bold;
            color:black;

            justify-self: center;
            padding-bottom: 1em;

            grid-column-start: 3;
            grid-column-end: 3;

            grid-row-start: 1;
            grid-row-end: 1;
        }

        .timeHeading {
            font-weight:bold;
            color:black;

            justify-self: center;
            padding-bottom: 1em;

            grid-column-start: 4;
            grid-column-end: 4;

            grid-row-start: 1;
            grid-row-end: 1;
        }

        .messageHeading {
            font-weight:bold;
            color:black;

            justify-self: center;
            padding-bottom: 1em;

            grid-column-start: 5;
            grid-column-end: 5;

            grid-row-start: 1;
            grid-row-end: 1;
        }

        .nameItem {
            justify-self: center;

            grid-column-start: 1;
            grid-column-end: 1;
            grid-row-start: auto;
            grid-row-end: auto;
        }

        .statusItemGreenDot {
            justify-self: center;

            background-color: greenyellow;
            height: 30px;
            width: 30px;
            border-radius: 50%;

            grid-column-start: 2;
            grid-column-end: 2;
            grid-row-start: auto;
            grid-row-end: auto;
        }
        .statusItemRedDot {
            justify-self: center;

            background-color: red;
            height: 30px;
            width: 30px;
            border-radius: 50%;

            grid-column-start: 2;
            grid-column-end: 2;
            grid-row-start: auto;
            grid-row-end: auto;
        }

        .statusCodeItem {
            justify-self: center;

            grid-column-start: 3;
            grid-column-end: 3;

            grid-row-start: auto;
            grid-row-end: auto;
        }

        .timeItem {
            justify-self: center;

            grid-column-start: 4;
            grid-column-end: 4;

            grid-row-start: auto;
            grid-row-end: auto;
        }

        .messageItem {
            justify-self: center;
            color: red;

            grid-column-start: 5;
            grid-column-end: 5;

            grid-row-start: auto;
            grid-row-end: auto;
        }
    </style>
</head>
<body>

    <?php

    foreach ($body as $check) {
        $dateTime = new DateTime();
        $dateTime->setTimestamp($check['check']['executed']);
        //echo "Name: " . $check["check"]["name"] . " Status: " . $check['check']["status"] . " Run at: " . $dateTime->format("d/m/Y H:i:s");
        //echo "<br />";
    }

    ?>

    <div id="app"></div>

    <script src="assets/js/app.bundle.js"></script>
</body>
</html>
